version: 2
jobs:
  build:
    docker:
      - image: quay.io/pantheon-public/php-ci:latest
    working_directory: ~/repo      
    steps:
      - checkout    
  deploy_pantheon:
    docker:
      - image: quay.io/pantheon-public/php-ci:latest
        environment:
          PANTHEON_TOKEN: 0AcZWq5i3Rp4_rpZ8sBLREynKFnlzb7RHxo4UE7q_sUyw   
          SITE_UUID: f50a1275-c05e-48de-8058-78e482a5784f     
    steps:
      - add_ssh_keys:
          fingerprints:
            - "30:26:cc:53:4c:7f:21:41:00:43:24:e5:96:57:38:62"      
      - checkout   
      - run:
          name: Deploying Pantheon Dev Environment
          command: |
            # Install Terminus
            curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install
            alias terminus=/home/circleci/project/vendor/bin/terminus
            terminus auth:login --machine-token=$PANTHEON_TOKEN
            mkdir -p $HOME/.terminus/plugins
            composer create-project -n -d $HOME/.terminus/plugins pantheon-systems/terminus-composer-plugin:~1
            composer create-project -n -d $HOME/.terminus/plugins pantheon-systems/terminus-build-tools-plugin:~1

            # Configure Pantheon Repository
            echo 'Host *' >> ~/.ssh/config
            echo '   StrictHostKeyChecking no' >> ~/.ssh/config            
            git remote add pantheon ssh://codeserver.dev.f50a1275-c05e-48de-8058-78e482a5784f@codeserver.dev.f50a1275-c05e-48de-8058-78e482a5784f.drush.in:2222/~/repository.git
            git remote -v

            # Push Pantheon
            git pull origin master 
            git push pantheon master     
workflows:
  version: 2
  build_and_deploy:
    jobs:      
      - deploy_pantheon        