version: 2
jobs: 
  deploy_multidev:
    docker:
      - image: quay.io/pantheon-public/php-ci:latest
        environment:
          PANTHEON_TOKEN: 0AcZWq5i3Rp4_rpZ8sBLREynKFnlzb7RHxo4UE7q_sUyw   
          SITE_UUID: f50a1275-c05e-48de-8058-78e482a5784f
          TERMINUS_SITE: gusto-poc     
    steps:
      - add_ssh_keys:
          fingerprints:
            - "30:26:cc:53:4c:7f:21:41:00:43:24:e5:96:57:38:62"      
      - checkout   
      - run: mkdir -p workspace
      - run:
          name: Deploying Pantheon Dev Environment
          command: |
            # Terminus
            terminus auth:login --machine-token=$PANTHEON_TOKEN
            mkdir -p $HOME/.terminus/plugins
            composer create-project -n -d $HOME/.terminus/plugins pantheon-systems/terminus-composer-plugin:~1
            composer create-project -n -d $HOME/.terminus/plugins pantheon-systems/terminus-build-tools-plugin:~1

            git config --global user.email "hmdelnegro@gmail.com"
            git config --global user.name "Marcelo"

            # Configure Pantheon Repository
            echo 'Host *' >> ~/.ssh/config
            echo '   StrictHostKeyChecking no' >> ~/.ssh/config  

            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              echo "It is a PR"
              echo $CIRCLE_PR_NUMBER              
              terminus build:env:create -n "$TERMINUS_SITE.dev" ci-$CIRCLE_PR_NUMBER --yes --clone-content --db-only
            fi
          
            pwd
            echo $CIRCLE_PR_NUMBER > workspace/circle-pr-number
            # git remote add pantheon ssh://codeserver.dev.f50a1275-c05e-48de-8058-78e482a5784f@codeserver.dev.f50a1275-c05e-48de-8058-78e482a5784f.drush.in:2222/~/repository.git
            # git remote -v

            # # Push Pantheon
            # git pull origin master 
            # git push pantheon master  
      - persist_to_workspace:
          root: workspace
          paths:
            - circle-pr-number            
  merge_multidev_to_dev:
    docker:
      - image: quay.io/pantheon-public/php-ci:latest
        environment:
          PANTHEON_TOKEN: 0AcZWq5i3Rp4_rpZ8sBLREynKFnlzb7RHxo4UE7q_sUyw   
          SITE_UUID: f50a1275-c05e-48de-8058-78e482a5784f
          TERMINUS_SITE: gusto-poc     
    steps:
      - add_ssh_keys:
          fingerprints:
            - "30:26:cc:53:4c:7f:21:41:00:43:24:e5:96:57:38:62"      
      - checkout   
      - attach_workspace:
          at: /root/project/workspace
      - run:
          name: Deploying Pantheon Dev Environment
          command: |
            # Terminus
            terminus auth:login --machine-token=$PANTHEON_TOKEN
            mkdir -p $HOME/.terminus/plugins
            composer create-project -n -d $HOME/.terminus/plugins pantheon-systems/terminus-composer-plugin:~1
            composer create-project -n -d $HOME/.terminus/plugins pantheon-systems/terminus-build-tools-plugin:~1   
            GITHUB_PR_NUMBER=$(cat /root/project/workspace/circle-pr-number)
            echo "Merge"
            echo $GITHUB_PR_NUMBER
            terminus build:env:merge $TERMINUS_SITE.${GITHUB_PR_NUMBER}
            echo "PR:"
            echo $CIRCLE_PR_NUMBER
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy_multidev:
          filters:  
            branches:
              only:  /gus-.*/
      - merge_multidev_to_dev:
          filters:  
            branches:
              only:  
                - master                
          