version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo      
    steps:
      - checkout    
  deploy_pantheon:
    docker:
      - image: circleci/node:8
        environment:
          PANTHEON_TOKEN: 0AcZWq5i3Rp4_rpZ8sBLREynKFnlzb7RHxo4UE7q_sUyw   
          SITE_UUID: f50a1275-c05e-48de-8058-78e482a5784f     
    steps:
      - add_ssh_keys:
          fingerprints:
            - "30:26:cc:53:4c:7f:21:41:00:43:24:e5:96:57:38:62"      
      - checkout   
      - run:
          name: Deploying Pantheon Dev Environment
          command: |
            # Origin=pantheon
            # Github=github
            git remote add pantheon ssh://codeserver.dev.f50a1275-c05e-48de-8058-78e482a5784f@codeserver.dev.f50a1275-c05e-48de-8058-78e482a5784f.drush.in:2222/~/repository.git
            git remote -v

            git fetch pantheon 
            # &&
            # git merge -m "Merge changes from pantheon into github" pantheon/master &&    
            # git push origin HEAD:master &&
            # git push pantheon HEAD:master;         
workflows:
  version: 2
  build_and_deploy:
    jobs:      
      - deploy_pantheon        